function [ power1, power2, power3, power4, power5, power6 ] = read_cambpower( file_name, scalarortensor,lnumber )
% Read in the power spectra generated by CAMB.

switch scalarortensor
    case 'scalar'
        pnumber=6;
    case 'tensor'
        pnumber=5;
    case 'lensed'
        pnumber=5;
end

fid=fopen(file_name,'r');
power_spectrum=fscanf(fid,'%g',[pnumber,lnumber]);

switch scalarortensor
    case 'scalar'
       power1=power_spectrum(1,:);
       power2=power_spectrum(2,:);
       power3=power_spectrum(3,:);
       power4=power_spectrum(4,:);
       power5=power_spectrum(5,:);
       power6=power_spectrum(6,:);

    case 'tensor'
       power1=power_spectrum(1,:);
       power2=power_spectrum(2,:);
       power3=power_spectrum(3,:);
       power4=power_spectrum(4,:);
       power5=power_spectrum(5,:);
       
    case 'lensed'
       power1=power_spectrum(1,:);
       power2=power_spectrum(2,:);
       power3=power_spectrum(3,:);
       power4=power_spectrum(4,:);
       power5=power_spectrum(5,:);
end
    
clear power_spectrum